server:
  port: 80
  
#durid
spring:
  thymeleaf:
    cache: false
  
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: validate
        
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://111.230.177.14:3306/xinjing?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: fy_C2mE
    
    druid:
      initial-size: 8 #初始化连接大小
      min-idle: 5 #最小空闲连接数
      max-active: 10 #最大连接数
      query-timeout: 6000 #查询超时时间
      transaction-query-timeout: 6000 #事务查询超时时间
      remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
      filter-class-names: stat
      filters: stat,config
      #initialSize: 5
      #minIdle: 5
      #maxActive: 20
      #maxWait: 100
      #timeBetweenEvictionRunsMillis: 60000
      #minEvictableIdleTimeMillis: 300000
      #validationQuery: SELECT 1 FROM DUAL
      #testWhileIdle: true
      #testOnBorrow: false
      #exceptionSorter: true
      #testOnReturn: false
      #poolPreparedStatements: true
      #filters: stat,wall,log4j
      #maxPoolPreparedStatementPerConnectionSize: 20
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      #useGlobalDataSourceStat: true
  redis:
    database: 0
    host: 111.230.177.14
    port: 6379
    password: fy_C2mE
    timeout: 30000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
        
     
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.gzggzy.yyh.model
  

    